title: "Research group wiki"
description: "Wiki for sharing procedures and information in research groups."
maintainer: "Adam Plowman"
baseurl: "/wiki"
github_user_or_organisation: aplowman
markdown: kramdown
kramdown:
  input: GFM
