title: Research group wiki
description: Wiki for sharing procedures and information in research groups.
maintainer: Joe Bloggs
github_user_or_organisation: aplowman
markdown: kramdown
kramdown:
  input: GFM
